### ISSUE TITLE
stress testing with qos=2 shows issues

### ISSUE THREAD

**Issue by schaefer01** [denglerchr/Mosquitto.jl#11]
hi,
It's not the mosquitto server because I've pre-tested using a python equivalent - I'm benchmarking who is faster, python or julia, and which is faster, MQTT or NATS, across varying block sizes. This is in preparation for a funded julia project to put julia processing close to sensors.

I'm using 2 consoles, setting qos=2, not all blocks are recieved, on retry but before publish, the subscriber immediately has a block, when I kill and restart the subscriber, it still immediately has a block.
Note too, that when I reset to qos=1. more blocks are received than qos = 2.

I'm adding my code as zip files and my invocation steps below, you'll need to change your path to the mqtt broker and your file paths to replicate what I've done. Each file is small and simple.

I haven't yet done the @time main() step to precompile (as I have for NATS benchmarking),
 but I can only work one problem at a time.

Thank you for your consideration,
  bob s

console 1:
> cd("./projects/senserf/julia")
> include("recv_mqtt_blk.jl") 
> main()

console 2:
> cd("./projects/senserf/julia")
> include("send_mqtt_blk.jl") 
> main()

[send_mqtt_blk.jl.zip](https://github.com/denglerchr/Mosquitto.jl/files/11895701/send_mqtt_blk.jl.zip)
[recv_mqtt_blk.jl.zip](https://github.com/denglerchr/Mosquitto.jl/files/11895702/recv_mqtt_blk.jl.zip)

**Comment by denglerchr** [comment]
Hello, I had a look, and I think the issue is in your case on sender side. When sending larger packets (not sure about how many bytes...), one single loop call might not be enough to get the message through. So there are 2 ways to fix this:
1) call loop more than once after each publish (there is an ntimes keyword argument for that). But this requires fiddling as it depends on message size, so I recommend instead
2) use the loop_forever function to run the loop asynchronously. Before today that function used to be blocking and required 2 Julia threads, but I changed something today, so if you run ]update, you should get a new version of the package and you can use the loop_forever like this in your sender script

```julia
using Mosquitto
using Printf
using Dates


function main()

  broker = "nebula.mit.edu"
  #broker = "localhost"
  println("starting MQTT publish, connecting to:", broker)
  
  # if client connection is not successfull, an @warn is sent
  client = Client(broker)
  if client.status.conn_status == true
    println("connect success, publishing...")
  end

  topic = "foo"  

  blksz = (32 * 1024)
  A = rand(ComplexF16, blksz)
  # B = reinterpret(Float16, A) # unnecessary
  C = reinterpret(UInt8, A)
  # D = String(C) # unnecessary

  println("orig length=",length(A))
  println("bytes=",length(C))
  
  # start loop, will return once client disconnects
  @async loop_forever(client)

  for _ = 1:1000
      Mosquitto.publish(client, topic, C; retain = true, qos = 2)
  end

  # wait a bit to give the network time to process everything before disconnecting
  println("Done, sleeping 2s to be sure messages are sent")
  sleep(2)
  disconnect(client)
end
```

**Comment by schaefer01** [comment]
thank you, I'm taking some time off from work for my neice's wedding and will get to this later next week

**Comment by schaefer01** [comment]
Hi,
 When I add the loop_forever, the subscriber receives no messages.
 I'm reattaching the receive with the loop forever commented out, and the loop() inside the async thread commented in.
 When the loop() is present, about 400 of 1000 messages are received.

Also, a different but related problem, the example on this page,   (https://github.com/denglerchr/Mosquitto.jl/tree/main/examples)/07_loop_forever.jl
which is referenced for using async, and what I used as a template in the code I am attaching,
the call "conncb = take!(get_connect_channel())" never returns
so I had to reuse my original example's call to connect

receive block:
[recv_mqtt_blk.jl.zip](https://github.com/denglerchr/Mosquitto.jl/files/11959177/recv_mqtt_blk.jl.zip)

**Comment by schaefer01** [comment]
I'm setting qos=2, could it be a qos issue? 
I assume the qos setting does some sort of handshaking to keep pub+broker+sub in sync.
The publisher in this instance appears to rip right through to the end, no stopping,
compared to julia nats, and python nats and mqtt. 
When I tested these, for python, for qos=1, I saw the publisher rip right through and the subscriber give up early, so this reminds me of that.

**Comment by denglerchr** [comment]
I took a look just now:
- When you use the loop_forever, you should remove the inner while loop, otherwise that loop just takes 100% of the CPU time of Julia and doesnt allow the callback function to put messages in the channel
- When one removes the inner while loop with loop_forever, or one uses the loop() manually, still some messages seem lost. The reason is that messages are put in a Channel of size 20 (Mosquitto.messages_channel) and I thought it would be a good idea to delete the oldest message if more messages arrive and the channel is full. Now this seems to not be such a good idea anymore, probably blocking and waiting for a message to be removed would be better. Ill think about changing this, or at least adding the option to have this behavior.

**Comment by denglerchr** [comment]
Bascially this part in https://github.com/denglerchr/Mosquitto.jl/blob/main/src/callbacks.jl can make messages disappear if too many arrive quickly, Ill see about this issue tomorrow
```julia
 # put it in the channel for further use
    if Base.n_avail(messages_channel)>=messages_channel.sz_max
        popfirst!(messages_channel)
    end
    put!(messages_channel, MessageCB(clientid, topic, jlpayload))
```

**Comment by denglerchr** [comment]
I did a larger update today, changing quite a few things. E.g., the messages are not deleted anymore by default and each client brings its own channels.
However, I found when publishing a lot of messages in a for loop like this, e.g., 5000 in a row, some can get lost sometimes on publisher side. I dont know why currently, but I found either putting a small wait between each message (sleep(0.001)) or a large amount of manual loops resolved it for me. The second option is included in the file here. Note that they need the new version 0.7 of this package
[code.zip](https://github.com/denglerchr/Mosquitto.jl/files/11985220/code.zip)

**Comment by denglerchr** [comment]
I think I solved it this morning, there is a `mosquitto_publish_callback_set` that can be used to check if a message arrived. Using this, I added a keyword argument `waitcb` to the publish function which makes the function return only after the message arrived at the broker. With this, I dont lose any messages anymore. To see how to use this `waitcb` you can check out the new example https://github.com/denglerchr/Mosquitto.jl/blob/main/examples/08_publish_loop_forever.jl , or just the appended files here [code.zip](https://github.com/denglerchr/Mosquitto.jl/files/11990287/code.zip), that hopefully solve your issue. 
Please note that you need to update the package to 0.7.1 to use said functionality.

**Comment by schaefer01** [comment]
hi, Christian,

  Is there a delay between when you update and when a user sees the update?

 Your code.zip raised an Error.

  I renamed your files _vcd.jl before use so I don't lose track of what I'm doing over time.

julia>  cd("./projects/senserf/julia")

julia> include("send_mqtt_blk_vcd.jl") 
main (generic function with 1 method)

julia> main(1000)
starting MQTT publish, connecting to:192.168.4.54
ERROR: type Client has no field conn_status
Stacktrace:
 [1] getproperty
   @ ./Base.jl:37 [inlined]
 [2] main(nmessages::Int64)
   @ Main ~/projects/senserf/julia/send_mqtt_blk_vcd.jl:20
 [3] top-level scope
   @ REPL[3]:1

**Comment by denglerchr** [comment]
Hmm no, for me it updates. Maybe there is some dependencies blocking the update, what if you specify "]update Mosquitto"? It should be version 0.7.1 as of 2 days ago (cf https://github.com/denglerchr/Mosquitto.jl/blob/main/Project.toml)

**Comment by schaefer01** [comment]
Hi,

  I did both, update and update Mosquitto

 Who is responsible at the julia organization for making sure updates are propagated in a timely manner?

(@v1.9) pkg> update Mosquitto
    Updating registry at `~/.julia/registries/General.toml`
  No Changes to `~/.julia/environments/v1.9/Project.toml`
  No Changes to `~/.julia/environments/v1.9/Manifest.toml`

(@v1.9) pkg> status Mosquitto
Status `~/.julia/environments/v1.9/Project.toml`
  [db317de6] Mosquitto v0.5.0 `~/.julia/dev/Mosquitto`

**Comment by denglerchr** [comment]
I get
```
 (@v1.9) pkg> update
    Updating registry at `~/.julia/registries/General.toml`
    Updating git-repo `https://github.com/denglerchr/Mosquitto.jl`
```
It seems to not check this repo for you, very strange... What if you do `rm Mosquitto` and `add https://github.com/denglerchr/Mosquitto.jl` afterwards?

**Comment by schaefer01** [comment]
That was it, thank you. 
I'll run the code again tomorrow.

(@v1.9) pkg> rm Mosquitto
    Updating `~/.julia/environments/v1.9/Project.toml`
  [db317de6] - Mosquitto v0.5.0 `~/.julia/dev/Mosquitto`
    Updating `~/.julia/environments/v1.9/Manifest.toml`
  [db317de6] - Mosquitto v0.5.0 `~/.julia/dev/Mosquitto`
  [458c3c95] - OpenSSL_jll v3.0.9+0
  [fe4c1bd5] - mosquitto_client_jll v2.0.15+0

(@v1.9) pkg> add https://github.com/denglerchr/Mosquitto.jl
    Updating git-repo `https://github.com/denglerchr/Mosquitto.jl`
   Resolving package versions...
    Updating `~/.julia/environments/v1.9/Project.toml`
  [db317de6] + Mosquitto v0.7.1 `https://github.com/denglerchr/Mosquitto.jl#main`
    Updating `~/.julia/environments/v1.9/Manifest.toml`
  [db317de6] + Mosquitto v0.7.1 `https://github.com/denglerchr/Mosquitto.jl#main`
  [458c3c95] + OpenSSL_jll v3.0.9+0
  [fe4c1bd5] + mosquitto_client_jll v2.0.15+0
Precompiling project...
  1 dependency successfully precompiled in 1 seconds. 50 already precompiled.

(@v1.9) pkg> status Mosquitto
Status `~/.julia/environments/v1.9/Project.toml`
  [db317de6] Mosquitto v0.7.1 `https://github.com/denglerchr/Mosquitto.jl#main`

**Comment by denglerchr** [comment]
Ah looks like you dev`ed the package, probably thats the reason it didnt update. Ok let me know if it works tomorrow.

**Comment by schaefer01** [comment]
for my education, for the future, if I "dev" a package I have to delete to update?

**Comment by denglerchr** [comment]
Hello, I never used the dev functionality, but according to the documentation, there should be a *free* command to put the package back to the git version.
https://pkgdocs.julialang.org/v1/managing-packages/

**Comment by schaefer01** [comment]
thank you.

I ran the code this morning without problem, however when I reran to get timing information, this is what happened:
> @time main(1000)
ERROR: syntax: ">" is not a unary operator
Stacktrace:
 [1] top-level scope
   @ none:1

My first thought was to find ">" but it is not in the source, which makes me think its in a library.
My second thought that this might be due to main taking parameters so I put the 1000 inside main, but
got no improvement:
@time main()
ERROR: syntax: ">" is not a unary operator
Stacktrace:
 [1] top-level scope
   @ none:1

I can work around this by adding timestamps to the code and doing math, but I'm curious as to why the error occurs.

**Comment by schaefer01** [comment]
Hi,
  I did my benchmarking and Mosqutto is 2 orders of magnitude slower than NATS but MQTT was also slower than NATS in python.
 Good news however, Mosqutto in juila is faster than Mosquitto in python, which makes sense if this is a julia wrapper on C code.
Any chance you are interesting in revisiting the underlying code to make  Mosquitto-julia more competitive against NATS-julia?

**Comment by denglerchr** [comment]
Hello,
If you can share some of that Julia NATS code I would be very interested to have a look. My current thoughts on this:
- NATS vs MQTT: 2 orders of magnitude sounds strange to me, I am not sure an apples to apples comparison is done here. If you can share some NATS code Id be interested to check.
- Julia vs Python: unless you have some kind of crazy network, this benchmark you put together will be bottlenecked by the network speed, not by the CPU. Therefore Im glad you can actually see some difference at all. Where Julia would shine is in quickly processing the data received.

**Comment by schaefer01** [comment]
hi,
  I agree with both your points.

  By benchmarking and comparing we wanted to better know the julia environment.

 The goal is to move from python to julia,  to put high power computation at a sensor, and to use high speed
   networking to get the information from the sensor to where needed.

  I varied the blocksize and reran each test 32K, 64K, 128K, 256K, and 512K (NATS has a block size limit so I stopped at 512).

 I'm also giving back the MQTT examples, that I renamed. I modified the send to get timing info since @time main() doesn't work.
[recv_mqtt_blk_vcd.jl.zip](https://github.com/denglerchr/Mosquitto.jl/files/12017240/recv_mqtt_blk_vcd.jl.zip)
[send_mqtt_blk_vcd.jl.zip](https://github.com/denglerchr/Mosquitto.jl/files/12017241/send_mqtt_blk_vcd.jl.zip)
[recv_nats_blk.jl.zip](https://github.com/denglerchr/Mosquitto.jl/files/12017242/recv_nats_blk.jl.zip)
[send_nats_blk.jl.zip](https://github.com/denglerchr/Mosquitto.jl/files/12017244/send_nats_blk.jl.zip)

**Comment by denglerchr** [comment]
For me the @time works with Mosquitto, I ran the benchmark with 10000 messages and the brokers on localhost. MQTT is slower by about 20% for me. 1.2s against 1.0s approx.
If you have a have differences in magnitude of 100x I would assume something is weird on broker/server side maybe. Not sure.

Note that I set "retain=false" and "qos=1" in MQTT. ". I am not sure what NATS provides in terms of guaranties for message arrival, so no idea what would be a fair setting here. 

NATS:
![NATS](https://github.com/denglerchr/Mosquitto.jl/assets/15248169/e8cdde43-970a-4c6d-a443-a0d5443e8f3d)

MQTT:
![MQTT](https://github.com/denglerchr/Mosquitto.jl/assets/15248169/64cf6b24-7156-4960-91b5-a3ccf8d22665)

**Comment by schaefer01** [comment]
I set qos=2, which I needed for the network else I got dropouts between publisher and subscriber.

  I just checked to make sure the code you sent me didn't revert back to qos=1, else I'd have to redo my tests,
    but I'm ok.  (I used qos =2 for NATS as well)

 I suggest testing using a network, even if the computers and the broker are sitting on the same LAN.

Too many real-world factors are bypassed when you use localhost.

**Comment by denglerchr** [comment]
I checked it today over an actual network.
- The NATS function returning does not mean, that all messages have been sent. Rather, the library puts them all in a Channel, and once they are all in the channel, the function returns already. If you, e.g., exit Julia right after the main() publishing call, you will find that not many messages arrive.
- Where in the NATS script do you set the QoS? I could not find such setting for the library.
- Comparing the actual speed on receiver side, I get the following on my setup here for 1000 messages
    - NATS QoS ?: ~18s (the publishing function returns in less than a second, but again, this doesnt mean the messages have been sent)
    - MQTT QoS 0: ~17s
    - MQTT QoS 1: ~25s
    - MQTT Qos 2: ~30s

**Comment by schaefer01** [comment]
NATS julia does not support setting the qos, I can't find the name qos in the julia src code visible when I loaded it with the dev option. However, its behavior when I have 2 subscribers and one of the subscribers is crippled or killed indicates that the broker is behaving as if the (default?) qos setting is 2.
