### ISSUE TITLE
Code formatting

### ISSUE THREAD

**Issue by scls19fr** [denglerchr/Mosquitto.jl#18]
Hello,

it could make the code cleaner by using https://github.com/domluna/JuliaFormatter.jl

Kind regards

PS : see also https://discourse.julialang.org/t/julia-code-formatter-code-beautifier/11485/21

**Comment by denglerchr** [comment]
Where do you see the badly formatted code? This is just a formatting tool, VSCode has it included

**Comment by denglerchr** [comment]
Code is formatted using VS Code formatter. I dont like some of the things the JuliaFormatter does. Closing this one
