### ISSUE TITLE
loop_start and loop_stop cwrapper

### ISSUE THREAD

**Issue by jsagerOffis** [denglerchr/Mosquitto.jl#24]
Hi,

I was wondering why the `loop_start` and `loop_stop` functions in `cwrapper.jl` are commented out? 
Adding them back in on a local branch and forwarding via `mqtt.jl` and seems to be working as expected.

We would like to add an MQTT interface to the [Mango.jl](https://github.com/OFFIS-DAI/Mango.jl) agent framework and this package seems to otherwise do everything we need.

Kind Regards

**Comment by denglerchr** [comment]
Hello, I left it commented out as the build instruction on say:

> 
> Build Dependencies
> ...
> - pthreads - for client library thread support. This is required to support the mosquitto_loop_start() and mosquitto_loop_stop() functions. If compiled without pthread support, the library isn't guaranteed to be thread safe.
> 
so I felt it might be risky and produce bugs. But tbh I never tested if it might work. I could investigate a bit on the weekend. I would however want to be sure things work not only under Linux but also Windows, not sure if you tested both?

**Comment by jsagerOffis** [comment]
I just tested on Windows 10 with Julia 1.10.4 and everything worked as expected.

**Comment by denglerchr** [comment]
I tested and added `loop_start` and `loop_stop` in 0.10, which is released and should be available in the package repository soon. They seem to work as intended, lets see if someone finds a way to break them.
