### ISSUE TITLE
Update to current c api

### ISSUE THREAD

**Issue by rr-sam** [denglerchr/Mosquitto.jl#5]
Hi,

I started using your lib a while ago with great success. We're moving to MQTTv5 and would like to use TLS-PSK as well. Any interest in updating the codebase to the [new c calls](http://mosquitto.org/api/files/mosquitto-h.html)?  I started working on patching your code, but figured it might be quicker this way. 

Thanks.

**Comment by denglerchr** [comment]
Hey, nice to hear that the lib is used by other people as well! I will have some time end of next week, I will then give it a try. All you need is the TLS support part, or full MQTTv5 functionality like properties?

**Comment by denglerchr** [comment]
I added the tls_psk_set for now, however, I dont have a configured broker to fully test it

**Comment by denglerchr** [comment]
@rr-sam can I close this issue, does tls_psk work for you?

**Comment by rr-sam** [comment]
Thank you for the updates to TLS-PSK. I'll try them out today. Just buried with work right now.
