### ISSUE TITLE
subscribe from different julia console/interpreter does not receive packets

### ISSUE THREAD

**Issue by schaefer01** [denglerchr/Mosquitto.jl#8]
hi,
  I got the publish and subscribe to work in a single julia console but when I redid the same steps for the subscribe with retain=true in a different julia console, no packets were ever received. Any help?

**Comment by schaefer01** [comment]
followup:
  I can publish from julia and receive with a python subscriber
 but I can't publish from python and receive with a julia subscriber
(the python publisher and subscriber run in different consoles and work with each other)

**Comment by denglerchr** [comment]
Hello, for me it works fine, are you calling the loop(client) function to receive the messages?

Here a small example:
1) start the receiver/subscriber in a terminal
```julia
using Mosquitto
client = Client("test.mosquitto.org")
topic = "test/abcdefg123"
subscribe(client, topic)

nmessages = 0
while nmessages < 20
    loop(client)
    while !isempty(Mosquitto.messages_channel)
        msg = take!(Mosquitto.messages_channel)
        nmessages += 1
        println(String(msg.payload))
    end
end

disconnect(client)
```

2) publish some messages
```julia
using Mosquitto
client = Client("test.mosquitto.org")
topic = "test/abcdefg123"

for i = 1:20
    publish(client, topic, "Message $i"; retain = false)
    loop(client)
    sleep(1)
end

disconnect(client)
```

For me this gives:
![image](https://github.com/denglerchr/Mosquitto.jl/assets/15248169/38639cb9-f9b6-4469-894e-9eb39d2ae3ee)


I can help you better if you show me the code that isnt working for you.

**Comment by schaefer01** [comment]
that was it, I did not have the loop(client) on the subscribe side

**Comment by schaefer01** [comment]
Christian,

thank you, that was it, I did not have the loop(client)  on the subscribe side

I’ll revisit and close the issue

bob s.

On Jun 21, 2023, at 2:49 PM, Christian Dengler ***@***.***> wrote:



Hello, for me it works fine, are you calling the loop(client) function to receive the messages?

Here a small example:

  1.  start the receiver/subscriber in a terminal

using Mosquitto
client = Client("test.mosquitto.org")
topic = "test/abcdefg123"
subscribe(client, topic)

nmessages = 0
while nmessages < 20
    loop(client)
    while !isempty(Mosquitto.messages_channel)
        msg = take!(Mosquitto.messages_channel)
        nmessages += 1
        println(String(msg.payload))
    end
end

disconnect(client)


  1.  publish some messages

using Mosquitto
client = Client("test.mosquitto.org")
topic = "test/abcdefg123"

for i = 1:20
    publish(client, topic, "Message $i"; retain = false)
    loop(client)
    sleep(1)
end

disconnect(client)


For me this gives:
[image]<https://user-images.githubusercontent.com/15248169/247696018-38639cb9-f9b6-4469-894e-9eb39d2ae3ee.png>

I can help you better if you show me the code that isnt working for you.
